### ISSUE TITLE
explore option to have Jekyll create a sitemap.xml

### ISSUE THREAD

**Issue by egonw** [NanoCommons/user-handbook#22]
That `sitemap.xml` helps search engines index the content. For example, check http://independent-software.com/generating-a-sitemap-xml-with-jekyll-without-a-plugin.html

This user handbook `sitemap.xml` should then be linked to from https://github.com/NanoCommons/nanocommons.github.io/blob/main/sitemap.xml

**Comment by thomasexner** [comment]
Sitemap.xlm is generated. Egon, can you do the linking to https://github.com/NanoCommons/nanocommons.github.io/blob/main/sitemap.xml?

**Comment by egonw** [comment]
Done.
